import { now, slugify, uuid } from '@buildr/utils';
import type { Page, Site, SiteSummary, SiteTheme } from '@buildr/types';
import type { CreateSiteInput, UpdateSiteInput } from '@buildr/schemas';
import { siteRepository } from '../repositories/site.repository.js';
import { publishedRepository } from '../repositories/published.repository.js';
import { submissionRepository } from '../repositories/submission.repository.js';
import {
  DEFAULT_THEME,
  createDefaultAnalytics,
  createDefaultSettings,
  createHomePage,
} from '../config/site-defaults.js';
import { AppError } from '../utils/response.js';

function toSummary(site: Site): SiteSummary {
  return {
    id: site.id,
    name: site.name,
    subdomain: site.subdomain,
    status: site.status,
    pageCount: site.pages.length,
    updatedAt: site.updatedAt,
    publishedAt: site.publishedAt,
  };
}

export class SiteService {
  async listForUser(userId: string): Promise<SiteSummary[]> {
    const sites = await siteRepository.findByUser(userId);
    return sites
      .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))
      .map(toSummary);
  }

  /** Fetch a site the user owns, or throw 404 (never reveals others' sites). */
  async getOwned(id: string, userId: string): Promise<Site> {
    const site = await siteRepository.findById(id);
    if (!site || site.userId !== userId) throw AppError.notFound('site');
    return site;
  }

  private async assertSubdomainFree(subdomain: string): Promise<void> {
    const existing = await siteRepository.findBySubdomain(subdomain);
    if (existing) {
      throw AppError.conflict('That subdomain is already taken', {
        field: 'subdomain',
      });
    }
  }

  async create(userId: string, input: CreateSiteInput): Promise<Site> {
    const subdomain = input.subdomain.toLowerCase();
    await this.assertSubdomainFree(subdomain);

    // Two-step: the home page needs the site id, generated by the repository.
    const site = await siteRepository.create({
      userId,
      name: input.name,
      subdomain,
      status: 'draft',
      theme: { ...DEFAULT_THEME },
      pages: [],
      settings: createDefaultSettings(),
      analytics: createDefaultAnalytics(),
    });

    const withHome = await siteRepository.update(site.id, {
      pages: [createHomePage(site.id)],
    });
    return withHome ?? site;
  }

  async update(
    id: string,
    userId: string,
    input: UpdateSiteInput,
  ): Promise<Site> {
    const site = await this.getOwned(id, userId);

    const patch: Partial<Site> = {};
    if (input.name !== undefined) patch.name = input.name;
    if (input.customDomain !== undefined) patch.customDomain = input.customDomain;
    if (input.status !== undefined) {
      patch.status = input.status;
      if (input.status === 'published') patch.publishedAt = now();
    }
    if (input.theme !== undefined) {
      patch.theme = { ...site.theme, ...input.theme };
    }

    // Unpublishing (status leaves "published") takes the live site offline.
    if (input.status !== undefined && input.status !== 'published') {
      const published = await publishedRepository.findById(id);
      if (published?.live) {
        await publishedRepository.upsert({
          ...published,
          live: false,
          updatedAt: now(),
        });
      }
    }

    const updated = await siteRepository.update(id, patch);
    return updated ?? site;
  }

  /** Remove a site's dependent records (published snapshot + submissions). */
  private async purgeSiteData(siteId: string): Promise<void> {
    await publishedRepository.delete(siteId);
    const subs = await submissionRepository.findBySite(siteId);
    await Promise.all(subs.map((s) => submissionRepository.delete(s.id)));
  }

  async remove(id: string, userId: string): Promise<void> {
    await this.getOwned(id, userId);
    await siteRepository.delete(id);
    await this.purgeSiteData(id);
  }

  async deleteAllForUser(userId: string): Promise<void> {
    const sites = await siteRepository.findByUser(userId);
    await Promise.all(
      sites.map(async (site) => {
        await siteRepository.delete(site.id);
        await this.purgeSiteData(site.id);
      }),
    );
  }

  async duplicate(id: string, userId: string): Promise<Site> {
    const source = await this.getOwned(id, userId);

    // Find a free subdomain: "<sub>-copy", then "-copy-2", etc.
    let subdomain = `${source.subdomain}-copy`.slice(0, 63);
    let attempt = 2;
    while (await siteRepository.findBySubdomain(subdomain)) {
      subdomain = `${source.subdomain}-copy-${attempt}`.slice(0, 63);
      attempt += 1;
    }

    const copy = await siteRepository.create({
      userId,
      name: `${source.name} (copy)`,
      subdomain,
      status: 'draft',
      theme: { ...source.theme },
      pages: [],
      settings: { ...source.settings },
      analytics: createDefaultAnalytics(),
    });

    // Re-key pages onto the new site id, preserving blocks.
    const pages: Page[] = source.pages.map((page) => ({
      ...page,
      id: uuid(),
      siteId: copy.id,
    }));
    const finished = await siteRepository.update(copy.id, { pages });
    return finished ?? copy;
  }

  /** Find a free subdomain derived from a base label. */
  private async freeSubdomain(base: string): Promise<string> {
    const root = (slugify(base) || 'site').slice(0, 55);
    let candidate = root;
    let attempt = 2;
    while (await siteRepository.findBySubdomain(candidate)) {
      candidate = `${root}-${attempt}`;
      attempt += 1;
    }
    return candidate;
  }

  /** Persist an AI-generated site (theme + pages) for a user. */
  async createFromGeneration(
    userId: string,
    generated: { name: string; theme: SiteTheme; pages: Page[] },
  ): Promise<Site> {
    const subdomain = await this.freeSubdomain(generated.name);
    const site = await siteRepository.create({
      userId,
      name: generated.name,
      subdomain,
      status: 'draft',
      theme: generated.theme,
      pages: [],
      settings: createDefaultSettings(),
      analytics: createDefaultAnalytics(),
    });

    const pages: Page[] =
      generated.pages.length > 0
        ? generated.pages.map((page, index) => ({
            ...page,
            siteId: site.id,
            isHome: index === 0,
          }))
        : [createHomePage(site.id)];

    const finished = await siteRepository.update(site.id, { pages });
    return finished ?? site;
  }
}

export const siteService = new SiteService();
